# Data Recording
dataset_folder_path: "/home/rosjaeger/rosbag_data/testing_data"
rosbag_naming_convention: "rosbag_"

world_name: "maze.sdf"
world_package: "gpp_gazebo"
map_name: "maze.yaml"
map_package: "mir_gazebo"

robot_launch_file: "robot.launch"
robot_launch_package: "mir_gazebo"

number_of_tests: 100

robot_spawn_position_x: 0.0
robot_spawn_position_y: 0.0
robot_spawn_orientation_yaw: 0.0

robot_target_position_x: 0.0
robot_target_position_y: 0.0
robot_target_orientation_yaw: 0.0